### ISSUE TITLE
conn.src Since option is ignored

### ISSUE THREAD

**Issue by piotr-cz** [morris/vinyl-ftp#22]
In fact, looks like whole the `VinylFtp.src` method is not being executed:
- using gulp (`gulp.src`)
- without gulp, as per docs (`fs.src`)

It is, however when using `ftp.src` but then files are not transferred (there's just MLSD command)

Version 0.4.1

Maybe the solution is to move this functionality out of src module into new newerThan method in filters like so:

```JS
	newerThan: function ( folder, options) {

		options = this.makeOptions( options );
		return this.filter( folder, function ( file, remote, cb ) {

			cb(null, !remote || file.stat.mtime > options.since );

		}, options );

	},
```

Another problem I found is that the `remote` variable (used in [filter](https://github.com/morris/vinyl-ftp/blob/master/lib/filter.js#L52)) is always undefined (because of [this](https://github.com/morris/vinyl-ftp/blob/master/lib/ftp.js#L297)), so all comparisons evaluate to true,

When I change the callback to `cb(null, files)`, I see that the files listed (so compared to later) are on the root of remote server, which doesn't help much.

solution could be to use just one method for source and destination or pass local and remote path as a constructor option.

Sorry for rolling upside down, I've searched interwebz for this feature and I'm not going back to Phing.

**Comment by morris** [comment]
The vinyl-ftp `src` method has nothing to do with `gulp.src` or  `fs.src` - it's for downloading via ftp and may be piped to `gulp.dest` for example. Unless you're downloading, using `gulp.src` with `since` and then piping to `ftp.dest` should work fine. There is a `newer` filter that is a little different - it compares every file's mtime with its remote counterpart, and uploads the file if it is newer.

No, the `remote` is only undefined if the file does not exist. Otherwise the file is passed to the callback inside the loop above.

**Comment by piotr-cz** [comment]
I see. I thought that the `since` option is for comparing local file timestamp; my bad.

I was looking for a functionality to upload files which are newer than given timestamp (which I store and update in config file) so the plugin does not have to compare all the passed files and upload just newer ones. If you are interested, I can make a pull request with such feature. At the moment I'm using this:

```js
var since = new Date(envOptions.since || 0);

gulp.src(globalOptions.patterns, {base: '.', buffer: false, since: since})
    .pipe(conn.filter(envOptions.path.local, function(localFile, remoteFile, callback) {
        callback(null, localFile.stat.mtime > since);
    }))
    .pipe(conn.dest(envOptions.path.remote));
```

As for comparing local file to remote counterpart, the remote variable is undefined, because the function is looking for remote file in the root directory on remote server. The problem is that filtering functions don't know about the remote path as it's being passed into the `dest` method (which comes later).

By the way, you may remove the options for filtering methods in the readme. These doesn't do anything and it's little confusing.
Other thing is that the [release page](https://github.com/morris/vinyl-ftp/releases) shows up v0.2.1 as the latest release

**Comment by morris** [comment]
The filter in your example is not needed because `gulp.src` with `since` will do only emit files changed after the specified time. Just pipe them to `conn.dest` and you're good.

I don't think there are any useless options in the readme. Which ones do you think are not doing anything?

The releases were missing, sorry. I fixed that just now, thank you!

**Comment by piotr-cz** [comment]
As you said before, `gulp.src` has nothing to do with `vinyl-ftp.src`. It's for downloading, and I'm interested in uploading files that have been modified since last upload.

`gulp-src` doesn't use the `since` option at all; see:
- [Gulp.prototype.src](https://github.com/gulpjs/gulp/blob/v3.8.11/index.js#L25) uses vinyl-fs.src
- [vinyl-fs.src options](https://github.com/wearefractal/vinyl-fs/blob/v1.0.0/lib/src/index.js#L19)

I mean, try yourself.

As for the usesless options, I was wrong. I see not that I can use `reload: true` inside filters (it's not obvious from docs).

**Comment by morris** [comment]
Yes it does: https://github.com/wearefractal/vinyl-fs/blob/v1.0.0/lib/src/index.js#L43 :-)

**Comment by piotr-cz** [comment]
true!

**Comment by piotr-cz** [comment]
but it's still not working for me.

So the is probably that latest stable release of Gulp (3.x) is using [vinyl.fs in version 0.3.0](https://github.com/gulpjs/gulp/blob/v3.9.0/package.json) and the `since` option came there in version 1.0.0

**Comment by piotr-cz** [comment]
Thanks for assistance.
Ignore my rants about the problem with path on remote server, I was passing path to local file.
